const keysLayout = [
  [
    {
      key: '~',
      keyRu: 'ё',
      keyCode: 192,
      code: 'Backquote',
    },
    {
      key: '1',
      keyRu: '1',
      keyCode: 49,
      code: 'Digit1',
    },
    {
      key: '2',
      keyRu: '2',
      keyCode: 50,
      code: 'Digit2',
    },
    {
      key: '3',
      keyRu: '3',
      keyCode: 51,
      code: 'Digit3',
    },
    {
      key: '4',
      keyRu: '4',
      keyCode: 52,
      code: 'Digit4',
    },
    {
      key: '5',
      keyRu: '5',
      keyCode: 53,
      code: 'Digit5',
    },
    {
      key: '6',
      keyRu: '6',
      keyCode: 54,
      code: 'Digit6',
    },
    {
      key: '7',
      keyRu: '7',
      keyCode: 55,
      code: 'Digit7',
    },
    {
      key: '8',
      keyRu: '8',
      keyCode: 56,
      code: 'Digit8',
    },
    {
      key: '9',
      keyRu: '9',
      keyCode: 57,
      code: 'Digit9',
    },
    {
      key: '0',
      keyRu: '0',
      keyCode: 48,
      code: 'Digit0',
    },
    {
      key: '-',
      keyRu: '-',
      keyCode: 189,
      code: 'Minus',
    },
    {
      key: '=',
      keyRu: '=',
      keyCode: 187,
      code: 'Equal',
    },
    {
      key: 'Backspace',
      keyCode: 8,
      code: 'Backspace',
      size: 'calc(35px/.339)',
    },
  ],
  [
    {
      key: 'Tab',
      keyCode: 9,
      code: 'Tab',
      size: 'calc(28px/.5)',
    },
    {
      key: 'q',
      keyRu: 'й',
      keyCode: 81,
      code: 'KeyQ',
    },
    {
      key: 'w',
      keyRu: 'ц',
      keyCode: 87,
      code: 'KeyW',
    },
    {
      key: 'e',
      keyRu: 'у',
      keyCode: 69,
      code: 'KeyE',
    },
    {
      key: 'r',
      keyRu: 'к',
      keyCode: 82,
      code: 'KeyR',
    },
    {
      key: 't',
      keyRu: 'е',
      keyCode: 84,
      code: 'KeyT',
    },
    {
      key: 'y',
      keyRu: 'н',
      keyCode: 89,
      code: 'KeyY',
    },
    {
      key: 'u',
      keyRu: 'г',
      keyCode: 85,
      code: 'KeyU',
    },
    {
      key: 'i',
      keyRu: 'ш',
      keyCode: 73,
      code: 'KeyI',
    },
    {
      key: 'o',
      keyRu: 'щ',
      keyCode: 79,
      code: 'KeyO',
    },
    {
      key: 'p',
      keyRu: 'з',
      keyCode: 80,
      code: 'KeyP',
    },
    {
      key: '[',
      keyRu: 'х',
      keyCode: 219,
      code: 'BracketLeft',
    },
    {
      key: ']',
      keyRu: 'ъ',
      keyCode: 221,
      code: 'BracketRight',
    },
    {
      key: '\\',
      keyRu: '\\',
      keyCode: 220,
      code: 'Backslash',
    },
    {
      key: 'Del',
      keyRu: 'Del',
      keyCode: 46,
      code: 'Delete',
    },
  ],
  [
    {
      key: 'Caps',
      keyCode: 20,
      code: 'CapsLock',
      size: 'calc(32px/.4)',
    },
    {
      key: 'a',
      keyRu: 'ф',
      keyCode: 65,
      code: 'KeyA',
    },
    {
      key: 's',
      keyRu: 'ы',
      keyCode: 83,
      code: 'KeyS',
    },
    {
      key: 'd',
      keyRu: 'в',
      keyCode: 68,
      code: 'KeyD',
    },
    {
      key: 'f',
      keyRu: 'а',
      keyCode: 70,
      code: 'KeyF',
    },
    {
      key: 'g',
      keyRu: 'п',
      keyCode: 71,
      code: 'KeyG',
    },
    {
      key: 'h',
      keyRu: 'р',
      keyCode: 72,
      code: 'KeyH',
    },
    {
      key: 'j',
      keyRu: 'о',
      keyCode: 74,
      code: 'KeyJ',
    },
    {
      key: 'k',
      keyRu: 'л',
      keyCode: 75,
      code: 'KeyK',
    },
    {
      key: 'l',
      keyRu: 'д',
      keyCode: 76,
      code: 'KeyL',
    },
    {
      key: ';',
      keyRu: 'ж',
      keyCode: 186,
      code: 'Semicolon',
    },
    {
      key: "'",
      keyRu: 'э',
      keyCode: 222,
      code: 'Quote',
    },
    {
      key: 'Enter',
      keyCode: 13,
      code: 'Enter',
      size: 'calc(37px/.35)',
    },
  ],
  [
    {
      key: 'Shift',
      keyCode: 16,
      code: 'ShiftLeft',
      size: 'calc(27px/.3)',
    },
    {
      key: 'z',
      keyRu: 'я',
      keyCode: 90,
      code: 'KeyZ',
    },
    {
      key: 'x',
      keyRu: 'ч',
      keyCode: 88,
      code: 'KeyX',
    },
    {
      key: 'c',
      keyRu: 'с',
      keyCode: 67,
      code: 'KeyC',
    },
    {
      key: 'v',
      keyRu: 'м',
      keyCode: 86,
      code: 'KeyV',
    },
    {
      key: 'b',
      keyRu: 'и',
      keyCode: 66,
      code: 'KeyB',
    },
    {
      key: 'n',
      keyRu: 'т',
      keyCode: 78,
      code: 'KeyN',
    },
    {
      key: 'm',
      keyRu: 'ь',
      keyCode: 77,
      code: 'KeyM',
    },
    {
      key: ',',
      keyRu: 'б',
      keyCode: 188,
      code: 'Comma',
    },
    {
      key: '.',
      keyRu: 'ю',
      keyCode: 190,
      code: 'Period',
    },
    {
      key: '/',
      keyRu: '.',
      keyCode: 191,
      code: 'Slash',
    },
    {
      key: '↑',
      keyRu: '↑',
      keyCode: 38,
      code: 'ArrowUp',
    },
    {
      key: 'Shift',
      keyCode: 16,
      code: 'ShiftRight',
      size: 'calc(29px/.3)',
    },
  ],
  [
    {
      key: 'Ctrl',
      keyCode: 17,
      code: 'ControlLeft',
      size: '50px',
    },
    {
      key: 'Win',
      keyCode: 91,
      code: 'MetaLeft',
      size: '50px',
    },
    {
      key: 'Alt',
      keyCode: 18,
      code: 'AltLeft',
      size: '50px',
    },
    {
      key: 'Space',
      keyCode: 32,
      code: 'Space',
      size: '265px',
    },
    {
      key: 'Alt',
      keyCode: 18,
      code: 'AltRight',
      size: '50px',
    },
    {
      key: '←',
      keyRu: '←',
      keyCode: 37,
      code: 'ArrowLeft',
    },
    {
      key: '↓',
      keyRu: '↓',
      keyCode: 40,
      code: 'ArrowDown',
    },
    {
      key: '→',
      keyRu: '→',
      keyCode: 39,
      code: 'ArrowRight',
    },
    {
      key: 'Ctrl',
      keyCode: 17,
      code: 'ControlRight',
      size: '50px',
    },
  ],
];
export default keysLayout;
